behaviors:
  AmyImitation:
    trainer_type: ppo
    keep_checkpoints: 100
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 15000
    checkpoint_interval: 50000
    threaded: true

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple

    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant

    reward_signals:
      extrinsic:
        strength: 1.0 
        gamma: 0.99

    behavioral_cloning:
      demo_path: "Assets/Demonstrations/AmyIm2.demo"
      steps: 1000000
      strength: 0.5