behaviors:
  AmyImitation:
    trainer_type: ppo
    keep_checkpoints: 100
    max_steps: 2000000
    time_horizon: 128
    summary_freq: 15000
    checkpoint_interval: 50000
    threaded: true

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple

    hyperparameters:
      batch_size: 256
      buffer_size: 4096
      learning_rate: 1.0e-4
      beta: 1.0e-3
      epsilon: 0.1
      lambd: 0.9
      num_epoch: 5
      learning_rate_schedule: linear

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.95